version: '3.7'

services:
  postgres:
    image: postgres:16.1
    restart: unless-stopped
    volumes:
      - './db/postgres:/var/lib/postgresql/data'
    ports:
      - '127.0.0.1:5433:5432'
    environment:
      POSTGRES_PASSWORD: root
      PGPASSWORD: root
